---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Chart.Name | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
    spec:
      containers:
        - name: "nginx"
          image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
          volumeMounts:
            - name: "html"
              mountPath: "/usr/share/nginx/html"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 80
      volumes:
        - name: "html"
          secret:
            secretName: {{ $.Release.Name | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name | quote }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  replicas: {{ $.Values.replicaCount }}
