---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
data:
  index.html: |
    {{- tpl ($.Files.Get "index.html") $ | b64enc | nindent 4 }}
